env:
  browser: true
  es2020: true

plugins:
  - import

extends:
  - airbnb-typescript/base

parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.json

rules:
  # ++variable is impossible to express in terms of the += operator
  no-plusplus: off

  no-restricted-syntax:
    - error

    - selector: ForInStatement
      message: for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.

    # Allow for..of statements: avoiding iterators completely is not really possible in our codebase,
    # and the .forEach() method, which is effectively a statement, looks too much like an expression
    # - selector: ForOfStatement
    #   message: iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.

    - selector: LabeledStatement
      message: Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.

    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
