{{- $name := include "app.projectName" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: {{ printf "mwt-%s-cd" $name }}
  namespace: {{ .Release.Namespace }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ printf "mwt-%s-deployment-cd" $name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - {{ $name }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ printf "mwt-%s-deployment-cd" $name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "mwt-%s-deployment-cd" $name }}
subjects:
  - kind: ServiceAccount
    name: {{ printf "mwt-%s-cd" $name }}
    namespace: {{ .Release.Namespace }}
...
