defaultSeverity: error

plugins:
  - stylelint-order

extends:
  - stylelint-config-standard-scss

rules:
  indentation: 4

  order/order:
    - - dollar-variables
      - custom-properties
      - declarations
      - rules

  order/properties-order:
    - - content

      # Outer layout
      - grid-area
      - grid-row
      - grid-row-start
      - grid-row-end
      - grid-column
      - grid-column-start
      - grid-column-end
      - order
      - align-self
      - justify-self
      - flex-grow
      - flex-shrink
      - vertical-align

      # Floating
      - float
      - clear

      # Positioning
      - position
      - top
      - right
      - bottom
      - left
      - z-index

      # Box model
      - box-sizing
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      # Display & inner layout
      - display
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-wrap
      - grid
      - grid-template
      - grid-template-areas
      - grid-template-rows
      - grid-template-columns
      - grid-auto-rows
      - grid-auto-columns
      - grid-auto-flow
      - grid-gap
      - grid-row-gap
      - grid-column-gap
      - gap
      - row-gap
      - column-gap
      - align-content
      - align-items
      - justify-content
      - justify-items
      - columns
      - column-span
      - column-width
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-rule-width

      - object-fit
      - overflow
      - overflow-x
      - overflow-y
      - overflow-scrolling
      - clip
      - border
      - border-width
      - border-top
      - border-top-width
      - border-right
      - border-right-width
      - border-bottom
      - border-bottom-width
      - border-left
      - border-left-width
      - border-spacing
      - border-collapse
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - border-top-image
      - border-right-image
      - border-bottom-image
      - border-left-image
      - border-corner-image
      - border-top-left-image
      - border-top-right-image
      - border-bottom-right-image
      - border-bottom-left-image
      - background
      - background-color
      - background-image
      - background-attachment
      - background-position
      - background-position-x
      - background-position-y
      - background-clip
      - background-origin
      - background-size
      - background-repeat
      - box-decoration-break
      - box-shadow
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - table-layout
      - caption-side
      - empty-cells
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - font
      - font-weight
      - font-style
      - font-variant
      - font-size-adjust
      - font-stretch
      - font-size
      - font-family
      - color
      - src
      - line-height
      - letter-spacing
      - quotes
      - counter-increment
      - counter-reset
      - -ms-writing-mode
      - text-align
      - text-align-last
      - text-decoration
      - text-emphasis
      - text-emphasis-position
      - text-emphasis-style
      - text-emphasis-color
      - text-indent
      - text-justify
      - text-outline
      - text-transform
      - text-wrap
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-shadow
      - white-space
      - word-spacing
      - word-wrap
      - word-break
      - overflow-wrap
      - tab-size
      - hyphens
      - interpolation-mode
      - visibility
      - opacity
      - filter
      - resize
      - cursor
      - pointer-events
      - user-select
      - unicode-bidi
      - direction
      - column-rule-style
      - column-rule-color
      - break-before
      - break-inside
      - break-after
      - page-break-before
      - page-break-inside
      - page-break-after
      - orphans
      - widows
      - zoom
      - max-zoom
      - min-zoom
      - user-zoom
      - orientation
      - fill
      - stroke
      - transition
      - transition-delay
      - transition-timing-function
      - transition-duration
      - transition-property
      - transform
      - transform-origin
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - animation-fill-mode
    - unspecified: bottom
