twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        locales: '%app.locales%'

    form_themes:
        - '@WebToolkit/form/form_theme.html.twig'

when@test:
    twig:
        strict_variables: true
