services:
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  mep_web_toolkit.file_storage_driver:
    class: Mep\WebToolkitBundle\FileStorage\Driver\S3FileStorageDriver
    arguments:
      $region: 'TODO'
      $endpointUrl: 'TOD'
      $key: 'TOD'
      $secret: 'TODO'
      $bucketName: 'TODO'
      $cdnUrl: 'TODO'
      $objectsKeyPrefix: 'TODO'
