name: Docker builds (release)

on:
  push:
    tags:
      - 'v[0-9]+*'

jobs:
  docker-build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository name
        run: echo "MWT_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Setup version tag
        run: echo "MWT_VERSION_TAG=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            BUILD_TYPE=prod
            COMMIT_HASH=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.MWT_REPOSITORY_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.MWT_REPOSITORY_NAME }}:${{ env.MWT_VERSION_TAG }}
          #  YOUR_DOCKERHUB_USER/${{ env.MWT_REPOSITORY_NAME }}:latest
          #  YOUR_DOCKERHUB_USER/${{ env.MWT_REPOSITORY_NAME }}:${{ env.MWT_VERSION_TAG }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MWT_REPOSITORY_NAME }}:latest
          cache-to: type=inline
