# !!! WARNING !!!
# This file uses reusable GitHub workflows directly from a repository managed by the MEP Agency team.
# While this feature is extremely convenient to keep all your workflows up-to-date automatically, you may prefer to
# clone the "mep-agency/web-toolkit-workflows" repo and manage it manually for stronger security.
#
# Feel free to choose the best option according to your security needs.
#
# @see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: GitHub Container Registry cleanup

on:
  # Enable manual trigger
  workflow_dispatch:
  # Schedule execution
  schedule:
    - cron: '0 3 * * *'

jobs:
  ghcr-cleanup:
    uses: mep-agency/web-toolkit-workflows/.github/workflows/ghcr-cleanup.yaml@main
    with:
      repository_owner: orgs/${{ github.repository_owner }} # "<user>" or "orgs/<org name>"
    secrets:
      gh_private_token: ${{ secrets.GH_PRIVATE_TOKEN }}
