name: Twig CI

on:
  push:
    paths:
      - .github/workflows/twig-ci.yml
      - 'templates/**'
      - composer.lock
  pull_request:
    paths:
      - .github/workflows/twig-ci.yml
      - 'templates/**'
      - composer.lock

jobs:
  twig-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
        env:
          COMPOSER_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}

      - uses: ramsey/composer-install@v1
        with:
          composer-options: --prefer-dist

      - name: Run Twig linter
        run: php bin/console lint:twig ./templates
