name: MWT - Container image build

on:
  workflow_call:
    inputs:
      image_name:
        description: The image name without tag (e.g. "my-org/my-image"). Defaults to "REPO_OWNER/REPO_NAME"
        type: string
        required: false
      tag_name:
        description: The new image will be pushed to this tag. This is also used for caching
        type: string
        required: true
      push_git_version_tag:
        description: Set this to "true" when building tagged releases. The Git tag must follow the format "v1.2.3"
        type: boolean
        required: false
        default: false
    secrets:
      registry_host:
        description: Container registry hostname
        required: true
      registry_username:
        description: Container registry username
        required: true
      registry_password:
        description: Container registry password
        required: true

jobs:
  container-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup image name
        run: |
          if [ "${{ inputs.image_name }}" == "" ]; then
            echo "MWT_IMAGE_NAME=${{ github.repository_owner }}/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          else
            echo "MWT_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV
          fi

      - name: Setup full additional image tag
        if: ${{ inputs.push_git_version_tag }}
        run: echo "MWT_FULL_ADDITIONAL_IMAGE_TAG=${{ secrets.registry_host }}/${{ env.MWT_IMAGE_NAME }}:${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Setup build type
        run: |
          if [ "${{ env.MWT_FULL_ADDITIONAL_IMAGE_TAG }}" == "" ]; then
            echo "MWT_BUILD_VERSION=${{ inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "MWT_BUILD_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to the container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry_host }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          provenance: false # Fix for https://github.com/docker/build-push-action/issues/820
          build-args: |
            BUILD_VERSION=${{ env.MWT_BUILD_VERSION }}
            COMMIT_HASH=${{ github.sha }}
          tags: |
            ${{ secrets.registry_host }}/${{ env.MWT_IMAGE_NAME }}:${{ inputs.tag_name }}
            ${{ env.MWT_FULL_ADDITIONAL_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.registry_host }}/${{ env.MWT_IMAGE_NAME }}:${{ inputs.tag_name }}
          cache-to: type=inline
