name: Docker builds (symfony-app-runtime)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-builds-symfony-app-runtime.yaml
      - docker/symfony-app-runtime/**

jobs:
  symfony-app-runtime_80_apache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/symfony-app-runtime
          file: ./docker/symfony-app-runtime/8.0-apache/Dockerfile
          push: true
          tags: mepagency/symfony-app-runtime:8.0-apache
