name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          # Composer
          -
            local_path: composer/packages/web-toolkit-bundle
            split_repository: web-toolkit-bundle
          -
            local_path: composer/projects/symfony-web-toolkit-skeleton
            split_repository: symfony-web-toolkit-skeleton

          # NPM
          -
            local_path: npm/web-toolkit-front-end
            split_repository: web-toolkit-front-end

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: '!startsWith(github.ref, ''refs/tags/'')'
        uses: symplify/monorepo-split-github-action@2.0
        with:
          package-directory: ${{ matrix.package.local_path }}
          split-repository-organization: 'mep-agency'
          split-repository-name: ${{ matrix.package.split_repository }}

          user-name: GitHub Action
          user-email: action@github.com

      # with tag
      -
        if: startsWith(github.ref, 'refs/tags/')
        uses: symplify/monorepo-split-github-action@2.0
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package-directory: ${{ matrix.package.local_path }}
          split-repository-organization: 'mep-agency'
          split-repository-name: ${{ matrix.package.split_repository }}

          user-name: GitHub Action
          user-email: action@github.com
